arch:
  - aarch64
  - amd64
description: "MQTT-Gateway for SAIC cars like MG5, ZS EV or Marvel R"
name: "SAIC MQTT Gateway (Python)"
image: "saicismartapi/saic-python-mqtt-gateway"
url: "https://github.com/SAIC-iSmart-API/saic-home-assistant-addon"
slug: "saic_python_mqtt_gateway"
stage: "experimental"
version: "0.2.0"
legacy: true
options:
  MQTT_URI: "tcp://localhost:1883"
  MQTT_USER: ""
  MQTT_PASSWORD: ""
  MQTT_TOPIC: ""
  SAIC_USER: null
  SAIC_PASSWORD: null
  SAIC_URI: ""
  ABRP_API_KEY: ""
  ABRP_USER_TOKEN: ""
  OPENWB_LP_MAP: ""
schema:
  MQTT_URI: str
  MQTT_USER: str?
  MQTT_PASSWORD: password?
  MQTT_TOPIC: str?
  SAIC_USER: str
  SAIC_PASSWORD: password
  SAIC_URI: str?
  ABRP_API_KEY: str?
  ABRP_USER_TOKEN: str?
  OPENWB_LP_MAP: str?
init: false
host_network: true
